package com.unipi.gkagkakis.GUI;

import com.unipi.gkagkakis.main.Main;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Locale;
import java.util.Map;

public class GUI extends JFrame {
    private JPanel MainPanel;
    private JTextField textField;
    private JLabel countryArea;
    private JLabel temperatureArea;
    private JLabel humidityArea;
    private JLabel windSpeedArea;
    private JLabel UVIndexArea;
    private JLabel weatherDescriptionArea;
    private JLabel Hint;
    private JButton searchButton;

    public GUI() {
        //τιτλος application
        setTitle("WeatherApp");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setContentPane(MainPanel);
        pack();
        setResizable(false);
        setVisible(true);
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);
        //listener για οταν παταω enter α πατιεται το Search Button
        textField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (!textField.getText().isEmpty()) {
                        searchButton.doClick();
                        return;
                    }
                    setLabelsToDefault();
                }
            }
        });
        //Λειτουργια button αναλογα το input που δωσαμε
        searchButton.addActionListener(e -> {
            String text = textField.getText();
            if (!text.isEmpty()) {
                String formattedtext = text.replaceAll("\\s+", "+");
                Map<String, String> weatherData = Main.makePOSTRequest(formattedtext, false);
                handleData(weatherData);
                return;
            }
            setLabelsToDefault();
        });
    }

    //εμφανιζει τα data στο app
    private void handleData(Map<String, String> weatherData) {
        if (weatherData.containsKey("Error")) {
            System.out.println(weatherData.get("Error"));
        } else {
            temperatureArea.setText(weatherData.get("Temperature"));
            countryArea.setText(weatherData.get("Country"));
            humidityArea.setText(weatherData.get("Humidity"));
            windSpeedArea.setText(weatherData.get("Wind Speed"));
            UVIndexArea.setText(weatherData.get("UV Index"));
            weatherDescriptionArea.setText(weatherData.get("Weather Description"));
        }
    }

    //αρχικοποιηση πεδιων αν δωσω κενο input
    private void setLabelsToDefault() {
        countryArea.setText("----");
        temperatureArea.setText("----");
        humidityArea.setText("----");
        windSpeedArea.setText("----");
        UVIndexArea.setText("----");
        weatherDescriptionArea.setText("----");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(10, 3, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel.setBackground(new Color(-13684172));
        MainPanel.setFocusable(false);
        MainPanel.setToolTipText("");
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial Narrow", Font.BOLD, 28, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-6614597));
        label1.setText("Welcome to our weather app!");
        MainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial Narrow", Font.BOLD, 28, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-6614597));
        label2.setText("Please enter a city to get detailed weather information!");
        MainPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, -1, 20, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-14042354));
        label3.setText("City Name:");
        MainPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(345, 27), null, 0, false));
        textField = new JTextField();
        textField.setBackground(new Color(-11776175));
        textField.setCaretColor(new Color(-5784832));
        Font textFieldFont = this.$$$getFont$$$("Consolas", Font.BOLD | Font.ITALIC, 18, textField.getFont());
        if (textFieldFont != null) textField.setFont(textFieldFont);
        textField.setForeground(new Color(-5784832));
        textField.setMargin(new Insets(4, 12, 4, 12));
        textField.setText("");
        textField.setToolTipText("City Name");
        MainPanel.add(textField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(218, 30), null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$("Monospaced", Font.BOLD, 26, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setForeground(new Color(-4510931));
        label4.setText("Country:");
        label4.setToolTipText("");
        MainPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(345, 27), null, 0, false));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$("Monospaced", Font.BOLD, 26, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setForeground(new Color(-4510931));
        label5.setText("Temperature:");
        MainPanel.add(label5, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(345, 27), null, 0, false));
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$("Monospaced", Font.BOLD, 26, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setForeground(new Color(-4510931));
        label6.setText("Wind Speed:");
        MainPanel.add(label6, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(345, 27), null, 0, false));
        final JLabel label7 = new JLabel();
        Font label7Font = this.$$$getFont$$$("Monospaced", Font.BOLD, 26, label7.getFont());
        if (label7Font != null) label7.setFont(label7Font);
        label7.setForeground(new Color(-4510931));
        label7.setText("UV Index:");
        MainPanel.add(label7, new com.intellij.uiDesigner.core.GridConstraints(8, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(345, 27), null, 0, false));
        final JLabel label8 = new JLabel();
        Font label8Font = this.$$$getFont$$$("Monospaced", Font.BOLD, 26, label8.getFont());
        if (label8Font != null) label8.setFont(label8Font);
        label8.setForeground(new Color(-4510931));
        label8.setText("Weather Description:");
        MainPanel.add(label8, new com.intellij.uiDesigner.core.GridConstraints(9, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(345, 27), null, 0, false));
        final JLabel label9 = new JLabel();
        Font label9Font = this.$$$getFont$$$("Monospaced", Font.BOLD, 26, label9.getFont());
        if (label9Font != null) label9.setFont(label9Font);
        label9.setForeground(new Color(-4510931));
        label9.setText("Humidity:");
        MainPanel.add(label9, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(345, 27), null, 0, false));
        countryArea = new JLabel();
        Font countryAreaFont = this.$$$getFont$$$(null, -1, 20, countryArea.getFont());
        if (countryAreaFont != null) countryArea.setFont(countryAreaFont);
        countryArea.setForeground(new Color(-4488411));
        countryArea.setText("----");
        MainPanel.add(countryArea, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        temperatureArea = new JLabel();
        Font temperatureAreaFont = this.$$$getFont$$$(null, -1, 20, temperatureArea.getFont());
        if (temperatureAreaFont != null) temperatureArea.setFont(temperatureAreaFont);
        temperatureArea.setForeground(new Color(-4488411));
        temperatureArea.setText("----");
        MainPanel.add(temperatureArea, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        humidityArea = new JLabel();
        Font humidityAreaFont = this.$$$getFont$$$(null, -1, 20, humidityArea.getFont());
        if (humidityAreaFont != null) humidityArea.setFont(humidityAreaFont);
        humidityArea.setForeground(new Color(-4488411));
        humidityArea.setText("----");
        MainPanel.add(humidityArea, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        windSpeedArea = new JLabel();
        Font windSpeedAreaFont = this.$$$getFont$$$(null, -1, 20, windSpeedArea.getFont());
        if (windSpeedAreaFont != null) windSpeedArea.setFont(windSpeedAreaFont);
        windSpeedArea.setForeground(new Color(-4488411));
        windSpeedArea.setText("----");
        MainPanel.add(windSpeedArea, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        UVIndexArea = new JLabel();
        Font UVIndexAreaFont = this.$$$getFont$$$(null, -1, 20, UVIndexArea.getFont());
        if (UVIndexAreaFont != null) UVIndexArea.setFont(UVIndexAreaFont);
        UVIndexArea.setForeground(new Color(-4488411));
        UVIndexArea.setText("----");
        MainPanel.add(UVIndexArea, new com.intellij.uiDesigner.core.GridConstraints(8, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        weatherDescriptionArea = new JLabel();
        Font weatherDescriptionAreaFont = this.$$$getFont$$$(null, -1, 20, weatherDescriptionArea.getFont());
        if (weatherDescriptionAreaFont != null) weatherDescriptionArea.setFont(weatherDescriptionAreaFont);
        weatherDescriptionArea.setForeground(new Color(-4488411));
        weatherDescriptionArea.setText("----");
        MainPanel.add(weatherDescriptionArea, new com.intellij.uiDesigner.core.GridConstraints(9, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Hint = new JLabel();
        Font HintFont = this.$$$getFont$$$("Arial Black", Font.BOLD | Font.ITALIC, -1, Hint.getFont());
        if (HintFont != null) Hint.setFont(HintFont);
        Hint.setForeground(new Color(-16747589));
        Hint.setText("*For best results, also add country next to city name!  ");
        MainPanel.add(Hint, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(345, 17), null, 0, false));
        searchButton = new JButton();
        searchButton.setText("Search");
        MainPanel.add(searchButton, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField.setNextFocusableComponent(searchButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
